name: media_picker_widget
description: A widget that picks media files from storage and allows you to place anywhere in the widget tree.
version: 0.0.9
homepage: https://github.com/rafid08/media_picker_widget

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  photo_manager: '>=2.2.0 <=3.0.0'
  sliding_up_panel: '>=2.0.0 <=3.0.0'
  image_picker: '>=0.8.2'

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: